FROM nvcr.io/nvidia/tensorrt:21.03-py3

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /base

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt-get update && apt-get install -y python3 python3-pip cmake wget llvm && \
    apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev && \ 
    apt-get install -y protobuf-compiler libprotobuf-dev

RUN python3 -m pip install --upgrade pip

RUN pip3 install numpy==1.18.0 opencv-python==4.2.0.32 configparser==5.0.2 six==1.16.0 future==0.18.2 \
    python-multipart uvicorn==0.14.0 fastapi==0.65.2 \
    requests torch==1.7.0 torchvision==0.8.0 onnx-simplifier==0.3.0 onnx==1.9.0

RUN pip3 install einops pyyaml gdown more-itertools

RUN git clone --recursive --branch v2020.1 https://github.com/inducer/pycuda.git && \
	cd pycuda && \
	python3 configure.py --cuda-root=/usr/local/cuda && \
	pip3 install -e . 

COPY . /base

RUN mkdir model logfile

RUN pip3 install gdown

RUN gdown 19BdhVbJh4IZmWWPSGfnn5cylNNdQgmYT -O model/transformer_decoder.trt && \
    gdown 1jpOk9FyQyYiJqL01rCvCUCp0ZfiJeR1z -O model/transformer_encoder.trt 

# RUN wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1wFePMC2Y9WwrIxNfAkfSbMYfUWQl_g1a' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1wFePMC2Y9WwrIxNfAkfSbMYfUWQl_g1a" -O model/transformer_decoder.trt && rm -rf /tmp/cookies.txt && \
#    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1cyXR5KKxtrXjZtXlRudeDYSr_64YCKPi' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1cyXR5KKxtrXjZtXlRudeDYSr_64YCKPi" -O model/transformer_encoder.trt && rm -rf /tmp/cookies.txt 

CMD nvidia-smi; sh start_service.sh


