FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

WORKDIR /base

RUN apt-get update && apt-get install -y python3 python3-pip cmake wget llvm && \
    apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev && \ 
    apt-get install -y protobuf-compiler=3.0.0-9.1ubuntu1 libprotobuf-dev=3.0.0-9.1ubuntu1

RUN pip3 install --upgrade pip

RUN pip3 install numpy==1.18.0 opencv-python==4.2.0.32 configparser==5.0.2 six==1.16.0 future==0.18.2 \
    python-multipart uvicorn==0.14.0 fastapi==0.65.2 \
    requests torch==1.7.0 torchvision==0.8.0 pycuda==2021.1 onnx-simplifier==0.3.0 onnx==1.9.0

RUN wget  -O tensortt.tar.gz https://aiclub.uit.edu.vn/storage/tensortt-7.2.2.3.tar.gz && tar -xf tensortt.tar.gz
RUN pip3 install TensorRT-7.2.2.3/python/tensorrt-7.2.2.3-cp36-none-linux_x86_64.whl einops pyyaml gdown more-itertools

COPY . /base

RUN wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Z48833l7sflFI2YBaM_kkzwvHmh6zQHP' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Z48833l7sflFI2YBaM_kkzwvHmh6zQHP" -O model/transformer_decoder.trt && rm -rf /tmp/cookies.txt && \
    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1LSLFEYBOKNE4O0siZiLvh3rASaFEsZQH' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LSLFEYBOKNE4O0siZiLvh3rASaFEsZQH" -O model/transformer_encoder.trt && rm -rf /tmp/cookies.txt 

CMD nvidia-smi; sh start_service.sh


