version: "3.9"
services:
    service:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: service_template
        ports:
            - 2331:80
        networks:
            - service_net
        restart: unless-stopped
        volumes:
            - ./:/base
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: 1
                device_ids: ['2']
                capabilities: [gpu]
networks:
    service_net:
        external: true
